site_name: Ariel A.
site_url: https://arielarigossi.github.io/blog/
theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky    
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
nav:
  - Home: 
    - Home: index.md
    - Roadmap: news.md
    - About me: about/about.md
  - Sections:
    - AI: sections/ai.md
    - Docker Container: sections/docker.md
    - GNU/Linux: sections/gnulinux.md
    - Neovim: sections/neovim.md
    - Systemd: sections/systemd.md
    - Tmux: sections/tmux.md
    - Virtual Machines: sections/virtualmachines.md
  - About: 
    - About me: about/about.md
  
palette: 
    # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

    # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Spanish
      link: /es/
      lang: es

plugins:
  - search

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math