site_name: Ariel A.
site_url: https://arielarigossi.github.io/blog/
theme:
  name: material
  features:
    - toc.integrate
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - toc.integrate
nav:
  - Home: 
    - Home: index.md
    - Roadmap: news.md
    - About me: about/about.md
  - Sections:
    - AI: sections/ai.md
    - Docker Container: sections/docker.md
    - GNU/Linux: sections/gnulinux.md
    - Neovim: sections/neovim.md
    - Systemd: sections/systemd.md
    - Tmux: sections/tmux.md
    - Virtual Machines: sections/virtualmachines.md
  - About: 
    - About me: about/about.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math